### ISSUE TITLE
The extension could not be loaded 

### ISSUE THREAD

**Issue by blockchainguard** [yashrs/safecopy#1]
The extension could not be loaded because it requires a later version of Java. To use this extension you will need to start Burp with the required or later Java version.

**Comment by yashrs** [comment]
Can you please tell me the output of `java -version`?

**Comment by yashrs** [comment]
Hi @blockchainguard, can you please try the latest release and tell me if it's fixed?

**Comment by yashrs** [comment]
https://github.com/yashrs/safecopy/releases/tag/0.11

**Comment by blockchainguard** [comment]
thanks  guys

**Comment by yashrs** [comment]
Marking as solved
